# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlanFrames
                                 A QGIS plugin
 Создание рамок для планов масштабов 1:500 1:1000 1:2000 1:5000
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-13
        copyright            : (C) 2019 by Alexey Kolesnikov
        email                : a.a.kolesnikov@sgugit.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlanFrames class from file PlanFrames.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plan_frames import PlanFrames
    return PlanFrames(iface)
